api_platform:
    title: Company Users API
    version: 4.0.11
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework.
        [Its source code](https://github.com/api-platform/demo) includes various examples, check it out!
        You may also be interested by [the GraphQL entrypoint](/graphql).
        [A PWA](/) and [an admin](/admin) are consuming this API.
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    graphql:
        graphql_playground: false
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    http_cache:
        public: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    serializer:
        hydra_prefix: true
    swagger:
        api_keys:
            jwtToken:
                name: Authorization
                type: header

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.filter.review.admin.user:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            $properties: { user: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    app.filter.review.admin.book:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            $properties: { book: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    app.filter.review.admin.rating:
        parent: 'api_platform.doctrine.orm.numeric_filter'
        arguments:
            $properties: { rating: ~ } ]
        tags: [ 'api_platform.filter' ]
