security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: true
    access_control:
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }

when@prod: &prod
    security:
        firewalls:
            main:
                access_token:
                    token_handler: App\Security\Http\AccessToken\Oidc\OidcDiscoveryTokenHandler

when@dev: *prod

when@test:
    security:
        firewalls:
            main:
                access_token:
                    token_handler:
                        oidc:
                            claim: 'email'
                            audience: '%env(OIDC_AUD)%'
                            issuers: [ '%env(OIDC_SERVER_URL)%' ]
                            algorithm: 'ES256'
                            keyset: '{"keys":[%env(OIDC_JWK)%]}'
